apiVersion: v1
kind: Service
metadata:
  name: nest-boilerplate-svc
spec:
  selector:
    app: nest-boilerplate
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: nest-boilerplate
spec:
  containers:
    - name: nest-boilerplate-postgres
      image: postgres:14.5
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
            name: nest-boilerplate-secret
    - name: nest-boilerplate-backend
      image: localhost:5000/nest-boilerplate/nest-boilerplate
      ports:
        - containerPort: 30001
      envFrom:
        - secretRef:
            name: nest-boilerplate-secret
