export enum PermissionEnum {
  USER_READ = 'USER_READ',
  USER_WRITE = 'USER_WRITE',
  USER_REMOVE = 'USER_REMOVE',
  MATCH_MAKE = 'MATCH_MAKE',
  MATCH_MANAGE = 'MATCH_MANAGE',
  ROLE_READ = 'ROLE_READ',
  ROLE_WRITE = 'ROLE_WRITE',
  ROLE_DELETE = 'ROLE_DELETE',
}
